name: force cleanup all artifacts
on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
# on:
#   pull_request:
#     types:
#       - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  TARGET: "vs"
  ARCH: arm64
  NO_FORCE: 1
  VS_VER: 17
  GA_CI_SECRET: ${{ secrets.CI_SECRET }}
  GH_TOKEN: ${{ secrets.CI_SECRET }}
  USE_ARTIFACT: true

jobs:

  cleanup-artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Log old artifacts for potential deletion
      if: github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
      uses: actions/github-script@v7.0.1
      env:
        GH_TOKEN: ${{ secrets.CI_SECRET }}
        REPO: ${{ github.repository }}
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
        BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
      with:
        script: |
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1000 // Fetches up to 1000 artifacts in one go
          });

          console.log("Starting force cleanup of all artifacts.");

          for (const artifact of artifacts.data.artifacts) {
            if (!artifact.expired) {
              console.log(`Deleting artifact: ${artifact.name}`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              console.log(`Deleted artifact: ${artifact.name}`);
            }
          }

          console.log("All artifacts have been deleted.");